Dada una matriz cuadrada de $n\times n$ representando una imagen, 
rota la imagen en 90 grados. Evita realizar copias de la matriz y 
solo aplica una transformación de manera directa. 

```python
input = [[1,2,3],[4,5,6],[7,8,9]]
output = [[7,4,1],[8,5,2],[9,6,3]]
```


In [136]:
import numpy as np

In [137]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

Via arrays sin crear un nuevo arreglo

In [138]:
def rotate(matrix):
    n =len(matrix)
    # ejemplo: dada la entrada
    # [[1,2,3],[4,5,6],[7,8,9]]
    
    for i in range(n):       # itero filas
        for j in range(i,n): # itero columnas hasta n desde i
            
            ### cambia simultaneamente los valores que se afectan 
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j] 
    ### hasta este punto obtenemos
    # [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
    
    # debemos invertir el orden de los valores
    for row in matrix:
        row.reverse()        
    return matrix

In [139]:
rotate(matrix)

[[7, 4, 1], [8, 5, 2], [9, 6, 3]]

Via arrays creando un nuevo arreglo

In [127]:
def rotate(matrix):
    matrix = matrix[::-1][:]
    return [[row[i] for row in matrix] for i in range(len(matrix))]     

In [128]:
rotate(matrix)

[[7, 4, 1], [8, 5, 2], [9, 6, 3]]

Via cambio de indices

In [53]:
def rotate_1(matrix):
    return np.array(matrix)[::-1].T

Via numpy

In [54]:
def rotate_2(matrix):
   return np.rot90(np.flip(matrix))

Via multiplicación de matrices (caro)

In [55]:
def rotate_3(matrix):
    A  = np.array(matrix)
    L = A.shape[0]
    
    # Matriz de permutacion
    P = np.flip(np.rot90(np.eye(L)))
    
    return A.T@P

Caso 3x3

In [56]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [57]:
np.array(x)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Espeja las filas y columnas

In [58]:
np.flip(np.array(x))

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

Usando numpy obtenemos

In [59]:
rotate_1(x)

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [60]:
rotate_2(x)

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

Via multiplicación de matrices

In [61]:
rotate_3(x)

array([[7., 4., 1.],
       [8., 5., 2.],
       [9., 6., 3.]])

In [62]:
np.array(x).T@np.array([[0,0,1],[0,1,0],[1,0,0]])

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

caso 4x4

In [63]:
x = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [64]:
np.array(x)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
np.array(x).T@np.array([[0,0,0,1],[0,0,1,0],[0,1,0,0],[1,0,0,0]])

array([[13,  9,  5,  1],
       [14, 10,  6,  2],
       [15, 11,  7,  3],
       [16, 12,  8,  4]])

In [66]:
np.array(x).T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

En términos de coordenadas la transformación esta dada por

\begin{equation}
(i,j) = (i, n - i)
\end{equation}

con $i=0,1,\dots$,n-1$