In [48]:
import numpy as np 
import torch 

Comparacion entre ```numpy``` y ```torch```

In [49]:
x_torch = torch.arange(12, dtype=torch.float32)

x_numpy = np.arange(12, dtype=np.float32)

Cantidad de elementos o forma de los vectores-tensores

In [50]:
x_torch.numel()

12

In [51]:
x_torch.shape

torch.Size([12])

In [52]:
x_torch.reshape(6,2)

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])

In [53]:
x_numpy.size

12

In [54]:
x_numpy.shape

(12,)

In [55]:
x_numpy.reshape(6,2)

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

Creación de ceros, unos o números aleatorios

In [56]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [57]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.random.randn(2,3)

array([[-1.25309185,  0.10110685, -0.89684804],
       [-0.09065417,  0.71472243, -0.07012938]])

In [59]:
torch.zeros((2,2))

tensor([[0., 0.],
        [0., 0.]])

In [60]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [61]:
torch.randn(2,3)

tensor([[-0.3699, -1.1417,  0.0053],
        [-0.2140,  2.0394, -0.8089]])

Extraer partes de arreglos o elementos. Juegue con el valor de N y analice que ocurre

In [62]:
N = 5

In [63]:
x_torch[1:N]

tensor([1., 2., 3., 4.])

In [64]:
x_numpy[1:N]

array([1., 2., 3., 4.], dtype=float32)

Algunas funciones y operaciones: observe las diferencias

In [65]:
torch.tanh(torch.tensor(0.1))

tensor(0.0997)

In [66]:
torch.tanh(0.1)

TypeError: tanh(): argument 'input' (position 1) must be Tensor, not float

In [67]:
np.tanh(0.1)

0.09966799462495582

In [68]:
torch.exp(torch.tensor(2))

tensor(7.3891)

In [69]:
np.exp(2)

7.38905609893065

In [70]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y)
print(x - y)
print( x * y)
print(x / y)
print(x ** y)

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])


In [71]:
x = np.array([1.0, 2, 4, 8])
y = np.array([2, 2, 2, 2])
print(x + y)
print(x - y)
print( x * y)
print(x / y)
print(x ** y)

[ 3.  4.  6. 10.]
[-1.  0.  2.  6.]
[ 2.  4.  8. 16.]
[0.5 1.  2.  4. ]
[ 1.  4. 16. 64.]


Concatenación

In [72]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [73]:
X = np.arange(12, dtype=np.float32).reshape((3,4))
Y = np.array([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

# Concatenar a lo largo del eje de las filas (verticalmente)
np.concatenate((X, Y), axis=0), np.concatenate((X, Y), axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

Tensores

Dos matrices de dimension (3,4) que corresponden a un solo objeto (en alta dimension)

In [74]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [75]:
np.arange(24).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Las operaciones se realizan componente a componente

In [76]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [77]:
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [78]:
A = np.arange(6, dtype=np.float32).reshape(2, 3)
B = A.copy()  # Assign a copy of A to B by allocating new memory
A, A + B

(array([[0., 1., 2.],
        [3., 4., 5.]], dtype=float32),
 array([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]], dtype=float32))

In [79]:
A*B

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.]], dtype=float32)