# Funciones

Pensaremos una función en ```python``` de manera similar a la que pensamos una función matemática. La palabra reservada para generar una función es ```def``` como también ```return``` para devolver *resultados*

In [ ]:
def mi_funcion(x):
  return x

Generalmente, los nombres de las funciones se escriben en minúscula como buena práctica. Los argumentos pueden o no definirse. También aconsejo como buena práctica definir los argumentos de entrada y de salida, es decir:

In [ ]:
def mi_funcion(x: float)-> float:
  return x

Es decir, especificamos los tipos de datos que entran y salen de nuestra función, esto permite trabajar de manera más rápida colaborativamente. Otra buena práctica es dar una pequeña explicación de lo que nuestra función hace:

In [ ]:
def mi_funcion(x: float)-> float:
  '''
    mi_funcion es una función identidad.
    Dada una entrada x retorna el mismo valor.
    input: x (float)
    output: x (float)
  '''
  return x

Utilicemos la función:

In [ ]:
x = 12

Es posible llamar a la función, especificando el nombre del argumento y en tal caso debemos respetar el orden de los mismos:

In [ ]:
mi_funcion(x = 12)

12

También podemos no utilizar los nombres y simplemente colocarlos en el orden correcto:

In [ ]:
mi_funcion(12)

12

Una alternativa:

In [ ]:
mi_funcion(x = x)

12

El "x" dado como nombre al argumento no es lo mismo que el "x" definido en la célula 3 de este notebook. Otra cosa importante es que documentar nuestras funciones como en la célula ```[2]``` nos permite utilizar un método intrínseco a las funciones en ```python``` que se llama ```help```

In [ ]:
help(mi_funcion)

Help on function mi_funcion in module __main__:

mi_funcion(x: float) -> float
    mi_funcion es una función identidad.
    Dada una entrada x retorna el mismo valor.
    input: x (float)
    output: x (float)



Vamos por un segundo ejemplo: forzando un error

In [ ]:
def nombre(x: float,y: float,z: float)-> float:
  '''
    Suma de tres números
  '''
  return x+y+z

In [ ]:
# Descomenta y ejecuta el comando de abajo!:
#nombre(1,2,'hola')

Recordando los primeros notebooks de estructuras de datos, utilizaremos una función de ```numpy``` para crear otra función!

In [ ]:
import numpy as np
import typing
from typing import List, Tuple

def svd_customizable(X: np.array ,full_matrices = False, more_matrices = True)-> Tuple[np.array]:
  '''
    SVD de mi forma
  '''
  U,S,V = np.linalg.svd(X,full_matrices = full_matrices)
  if not more_matrices:
    return S
  if more_matrices:
    return U,S,V

Observa que fue necesario importar desde ```typing``` para especificar tipos de datos más complejos. Hasta el momento solo habíamos utilizado ```float```. Por otro lado, la función utiliza ```np.linalg.svd```y la idea es darle parámetros de entrada específicos. En este caso queremos utilizar uno de los dos modos ```full_matrices``` que el método ofrece y retornar 1 o 3 matrices si lo necesitaramos.

In [ ]:
M = np.random.rand(2,2)
svd_customizable(M, more_matrices = True)

(array([[-0.19305513, -0.98118791],
        [-0.98118791,  0.19305513]]),
 array([0.77754076, 0.17173669]),
 array([[-0.89365389, -0.44875687],
        [ 0.44875687, -0.89365389]]))

Ahora observa esta serie de ejemplos, intenta jugar con ellos, cambiar cosas y experimentar tus propios códigos

Ejemplo 1

In [1]:
def hola_n_veces(n):
  """ describe tu el codigo AQUi!"""
  print('hola '*n)

In [5]:
hola_n_veces(3.0)

TypeError: ignored

In [3]:
def hola_n_veces_v01(n:int):
  """ describe tu el codigo AQUi!"""
  print('hola '*n)

In [4]:
hola_n_veces_v01(3)

hola hola hola 


Ejemplo 2

In [6]:
def fib(n):
    """describe tu el codigo AQUi!"""
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

In [7]:
fib(4)

0 1 1 2 3 


Ejemplo 3

In [13]:
def ask_ok(prompt, retries=4, reminder='Intentalo de nuevo!'):
  '''
  describe tu el codigo AQUi!
  '''
  while True:
      ok = input(prompt)
      if ok in ('s', 'si', 'sip', ' sí', ' si', 'sí'):
          return "vamos a comprar"
      if ok in ('n', 'no', 'nop', 'nope'):
          return "por qué dices eso?"
      retries = retries - 1
      if retries < 0:
          raise ValueError('respuesta inválida')
      print(reminder)

In [14]:
ask_ok(prompt = 'esta buena la fiesta?')

esta buena la fiesta?sí


'vamos a comprar'

Ejemplo cuatro: argumentos posicionales

In [ ]:
def parrot(voltage, state='a stiff', action='voom', type='Norwegian Blue'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.")
    print("-- Lovely plumage, the", type)
    print("-- It's", state, "!")

In [ ]:
parrot(1000)                                          # 1 argument posicional

-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !


In [ ]:
parrot(voltage=1000)        # 1 palabra clave o keyword

-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !


In [ ]:
parrot(voltage=1000000, action='VOOOOOM')             # 2 palabras claves

-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !


In [ ]:
parrot('a thousand', state='pushing up the daisies')  # 1 argument posicional y 1 key word

-- This parrot wouldn't voom if you put a thousand volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's pushing up the daisies !


Formas inválidas

In [ ]:
## Descomenta para observar los diferentes errores
#parrot()                     # required argument missing
#parrot(voltage=5.0, 'dead')  # non-keyword argument after a keyword argument
#parrot(110, voltage=220)     # duplicate value for the same argument
#parrot(actor='John Cleese')  # unknown keyword argument

Entregando argumentos y palabras claves al mismo tiempo

In [ ]:
def una_funcion_rara(kind, *arguments, **keywords):
    print("-- Tendrán alguna", kind, "?")
    print("-- Lo siento, no tenemos ninguna", kind)
    for arg in arguments:
        print(arg)
    print("-" * 40)
    for kw in keywords:
        print(kw, ":", keywords[kw])

In [ ]:
una_funcion_rara("Hamburguesa vegana", "Nunca me habia pasado",
           "Nunca nunca me habia pasado esto",
           vendedor_de_libros="Armando Uribe",
           cliente="John Cena",
           ambiente="cafe")

-- Tendrán alguna Hamburguesa vegana ?
-- Lo siento, no tenemos ninguna Hamburguesa vegana
Nunca me habia pasado
Nunca nunca me habia pasado esto
----------------------------------------
vendedor_de_libros : Armando Uribe
cliente : John Cena
ambiente : cafe


Utilizando diccionarios!

Esta forma de definir ```def una_funcion_rara(kind, *arguments, **keywords):``` permite entrar con diccionarios respetando la cantidad de argumentos posicionales y los nombres de las keywords.

In [ ]:
arguments = ["Nunca me habia pasado","Nunca nunca me habia pasado esto"]
keywords = {"vendedor_de_libros": "Armando Uribe", "cliente": "John Cena", "ambiente": "cafe"}

In [ ]:
una_funcion_rara("Hamburguesa vegana", *arguments, **keywords)

-- Tendrán alguna Hamburguesa vegana ?
-- Lo siento, no tenemos ninguna Hamburguesa vegana
Nunca me habia pasado
Nunca nunca me habia pasado esto
----------------------------------------
vendedor_de_libros : Armando Uribe
cliente : John Cena
ambiente : cafe


# Clases

Una clase es un objeto que contiene funciones. Una clase representa un objeto que tiene diferentes características, posibles de utilizar en diferentes momentos o que en su totalidad interactúan para caracterizar a tal objeto. La palabra reservada para crear una clase es ```class```y generalmente se nombran con letras mayúsculas al inicio de cualquier palabra nueva. Por ejemplo:

In [ ]:
class Gato:
  # inicializar mi clase
  def __init__(self,nombre:str, edad:str, peso: float):
    self.nombre = nombre #atributo 1
    self.edad = edad     #atributo 2
    self.peso = peso     #atributo 3
  #método de mi clase
  def como_te_llamas(self):
    print("me llamo ", self.nombre)

Definamos un "objeto" gato

In [ ]:
nombre = "Gal"
edad = "8 meses"
peso = 3.8

Inicializamos

In [ ]:
mi_gato = Gato(nombre=nombre, edad=edad, peso=peso)

In [ ]:
mi_gato.como_te_llamas()

me llamo  Gal


In [ ]:
mi_gato.edad

'8 meses'

podemos utilizar la clase para definir otro gato

In [ ]:
nombre = "Nina"
edad = "8 meses"
peso = 3.1

In [ ]:
mi_otro_gato = Gato(nombre=nombre, edad=edad, peso=peso)

In [ ]:
mi_otro_gato.como_te_llamas()

me llamo  Nina


Entendiendo ```self```

Veamos una forma no convencional de escribir una clase, solo a modo de ejemplo

In [ ]:
class Punto:
  def __init__(cualquier_cosa,a,b):
    cualquier_cosa.x = a
    cualquier_cosa.y = b
    print(cualquier_cosa)

In [ ]:
objeto_1 = Punto(3,4)

In [ ]:
objeto_1.x

3

In [ ]:
objeto_1.y

4

In [ ]:
Punto(3,4).x

3

Aproximemonos a la convención:

In [ ]:
class Punto2:
  def __init__(self,a,b):
    self.x = a
    self.y = b

In [ ]:
objeto_2 = Punto2(1,2)

In [ ]:
objeto_2.x

1

Forma convencional

In [ ]:
class Punto3:
  def __init__(self,x,y):
    self.x = x
    self.y = y

In [ ]:
help(Punto3)

Help on class Punto3 in module __main__:

class Punto3(builtins.object)
 |  Punto3(x, y)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, x, y)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



Idealmente es mejor describir nuestro código

In [ ]:
class Punto4:
  '''
    Clase que permite guardar las coordenadas
    de un punto en el plano cartesiano. Argumentos
    requeridos para inicializar:
    x : coordenada del eje de las abscisas
    y: coordenada del eje de las ordenadas
  '''
  def __init__(self,x: float,y: float):
    self.x = x
    self.y = y

In [ ]:
help(Punto4)

Help on class Punto4 in module __main__:

class Punto4(builtins.object)
 |  Punto4(x: float, y: float)
 |  
 |  Clase que permite guardar las coordenadas 
 |  de un punto en el plano cartesiano. Argumentos
 |  requeridos para inicializar:
 |  x : coordenada del eje de las abscisas
 |  y: coordenada del eje de las ordenadas
 |  
 |  Methods defined here:
 |  
 |  __init__(self, x: float, y: float)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



Agreguémos métodos a nuestra clase "Punto"

In [ ]:
import math
class Punto:
  '''
    Clase que permite guardar las coordenadas
    de un punto en el plano cartesiano. Argumentos
    requeridos para inicializar:
    x : coordenada del eje de las abscisas
    y: coordenada del eje de las ordenadas
  '''
  def __init__(self,x: float,y: float):
    self.x = x
    self.y = y
  def my_method(self, z: object):
    '''
      Calcula la distancia entre z y el punto de
      coordenadas (x,y). En este caso z = (z_1,z_2)
    '''
    return math.sqrt((self.x-z.x)**2 + (self.y-z.y)**2)

Definimos dos puntos

In [ ]:
X = Punto(1,1)
Z = Punto(2,2)

Calculamos la distancia

In [ ]:
X.my_method(Z)

1.4142135623730951

Podemos hacer que una clase "herede" los métodos de otra clase!

En esta clase solo tenemos un metodo que permite medir la distancia entre puntos

In [ ]:
import numpy as np
import math

class OtrasMetricas:
  def my_method(p1: object, p2: object):
    '''
      Calcula la distancia entre z y el punto de
      coordenadas (x,y). En este caso z = (z_1,z_2)
    '''
    return math.sqrt((p1.x-p2.x)**2 + (p1.y-p2.y)**2)

Este método recibe como herencia la clase anterior y ademas permite definir puntos

In [ ]:
class PuntoHerencia(OtrasMetricas):
  '''
    Clase que permite guardar las coordenadas
    de un punto en el plano cartesiano. Argumentos
    requeridos para inicializar:
    x : coordenada del eje de las abscisas
    y: coordenada del eje de las ordenadas
  '''
  def __init__(self,x: float,y: float):
    self.x = x
    self.y = y

Definimos dos puntos

In [ ]:
X = PuntoHerencia(1,1)
Z = PuntoHerencia(2,2)

Si observamos el help ahora el metodo continene la herencia

In [ ]:
help(PuntoHerencia)

Help on class PuntoHerencia in module __main__:

class PuntoHerencia(OtrasMetricas)
 |  PuntoHerencia(x: float, y: float)
 |  
 |  Clase que permite guardar las coordenadas 
 |  de un punto en el plano cartesiano. Argumentos
 |  requeridos para inicializar:
 |  x : coordenada del eje de las abscisas
 |  y: coordenada del eje de las ordenadas
 |  
 |  Method resolution order:
 |      PuntoHerencia
 |      OtrasMetricas
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, x: float, y: float)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from OtrasMetricas:
 |  
 |  my_method(p1: object, p2: object)
 |      Calcula la distancia entre z y el punto de
 |      coordenadas (x,y). En este caso z = (z_1,z_2)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from OtrasMetricas:
 |  
 |

In [ ]:
X.my_method(Z)

1.4142135623730951

In [ ]:
Z.my_method(Z)

0.0

In [ ]:
Z.my_method(X)

1.4142135623730951

La mayoría de los modelos de machine learning y deep learning actuarán como clases, entrenar, inferir y modificar parámetros será, generalmente, realizado a través de métodos de clases.