In [10]:
import librosa
import pathlib
from pathlib import Path
import os
import numpy as np 

Preprocesamiento

In [2]:
main_path = os.getcwd()
MyPath = pathlib.Path(main_path)

In [3]:
sr = 8000
kick_signals = [
    librosa.load(p, sr = sr)[0] for p in MyPath.glob('data/kick/Copia de Bass Sample *.wav')
]

snare_signals = [
    librosa.load(p, sr = sr)[0] for p in MyPath.glob('data/snare/Copia de Snare Sample *.wav')
]

In [4]:
len(kick_signals)

40

In [5]:
kick_signals[0]

array([-2.6417844e-04,  8.1657385e-03,  3.7222814e-02, ...,
        7.4974168e-06,  7.3690271e-06,  1.5755152e-06], dtype=float32)

In [9]:
len(kick_signals[0])

16000

In [7]:
mel_spectrogram = librosa.feature.melspectrogram(y = kick_signals[0],sr=sr,n_fft = 2048, hop_length = 512, n_mels = 10)

CNN 2D: representacion en escala de grises (tiene 1 canal)

In [8]:
mel_spectrogram.shape

(10, 32)

In [15]:
mel_spectrogram

array([[7.57863998e+01, 5.83792305e+01, 9.56376457e+00, 1.51304185e+00,
        3.69710714e-01, 1.42791748e-01, 6.97535425e-02, 3.55427079e-02,
        2.11162549e-02, 1.25802588e-02, 7.49214459e-03, 4.63804603e-03,
        2.92340666e-03, 1.86335330e-03, 1.18599168e-03, 7.04249367e-04,
        3.90759436e-04, 2.29217214e-04, 1.10093606e-04, 5.24141215e-05,
        2.98270825e-05, 1.57435024e-05, 7.16436807e-06, 4.63435708e-06,
        2.92145387e-06, 2.07571520e-06, 1.39810891e-06, 8.83835128e-07,
        5.34963249e-07, 3.67675483e-07, 2.93696786e-07, 1.26348482e-07],
       [1.05946314e+00, 5.89180231e-01, 1.17063873e-01, 2.60549653e-02,
        5.70048904e-03, 2.04701023e-03, 6.57930854e-04, 3.68067092e-04,
        2.38951587e-04, 1.72035507e-04, 7.97427492e-05, 3.48747635e-05,
        2.29975649e-05, 1.31811803e-05, 1.00689977e-05, 8.54767768e-06,
        4.82551695e-06, 4.01184752e-06, 2.20318429e-06, 1.11879024e-06,
        6.72041040e-07, 3.58184138e-07, 2.13000831e-07, 1.27824

In [17]:
np.save("my_base_de_datos_mel.npy",mel_spectrogram)

CNN 1D: promediar las pseudo-frecuencias de mel_spectrogram

In [13]:
mel_spectrogram_mean_por_bin_de_frecuencia = np.mean(mel_spectrogram, axis = 1)

In [14]:
mel_spectrogram_mean_por_bin_de_frecuencia.shape

(10,)

In [16]:
mel_spectrogram_mean_por_bin_de_frecuencia

array([4.5597992e+00, 5.6285307e-02, 1.4737563e-02, 1.1111571e-02,
       6.8585570e-03, 5.7122470e-03, 2.5070317e-03, 1.6914780e-03,
       1.0606776e-03, 6.3369598e-04], dtype=float32)

Emociones

In [18]:
1444/8

180.5

In [19]:
import json

In [20]:
my_json_structure = {"0":{"mel-spectrogram":mel_spectrogram, "target":0 }, "1":{"mel-spectrogram":mel_spectrogram, "target":1 }}

In [22]:
my_json_structure.keys()

dict_keys(['0', '1'])

In [25]:
mi_lista_de_mel_spec = []
targets = []
for key in my_json_structure.keys():
    mi_lista_de_mel_spec.append(my_json_structure[key]['mel-spectrogram'])
    targets.append(my_json_structure[key]['target'])

In [27]:
len(mi_lista_de_mel_spec)

2

In [28]:
len(targets)

2