**Revisando instrucciones básicas para trabajar DS en python 09/12/2021**

Solo cubriré algunos aspectos, lo que directamente usaremos para ejemplos sencillos de DS. Para ejecutar las células debes presionar shift + Enter

**Operaciones básicas en $\mathtt{python}$**

suma

In [ ]:
3+3

6

multiplicación

In [ ]:
3*3

9

potencias

In [ ]:
2**8

256

división

In [ ]:
3/2

1.5

división entera

In [ ]:
3//2

1

módulo

In [ ]:
20%2

0

creación de variables

In [ ]:
x = 3
y = 4

z = x+y

print(z)

7


**Ciclos**

Comenzamos por el ciclo *for*, observar que utilizamos indentación!

In [ ]:
for i in [1,2,3]:
  print(i)

1
2
3


In [ ]:
for i in range(3):
  print(i)

0
1
2


In [ ]:
x = [1,2,3]
for element in x:
  print(element)

1
2
3


In [ ]:
x = 2
for i in range(5):
  print(x+i)


2
3
4
5
6


ahora revisaremos *while*

In [ ]:
error = 100
tau = 90 

In [ ]:
error -=1

In [ ]:
error

99

In [ ]:
contador = 0
while error > tau:
  contador +=1
  error -= 1 
  print("iteración número: ", contador)
  print("Error:")
  print(error)

iteración número:  1
Error:
98
iteración número:  2
Error:
97
iteración número:  3
Error:
96
iteración número:  4
Error:
95
iteración número:  5
Error:
94
iteración número:  6
Error:
93
iteración número:  7
Error:
92
iteración número:  8
Error:
91
iteración número:  9
Error:
90


Condiciones *if*, *break*, *pass*:

In [ ]:
for i in range(5):
  print("iteracion: ", i)
  if i >= 2:
    print("mayor o igual que dos!")

iteracion:  0
iteracion:  1
iteracion:  2
mayor o igual que dos!
iteracion:  3
mayor o igual que dos!
iteracion:  4
mayor o igual que dos!


In [ ]:
for i in range(6):
  print("iteracion: ", i)
  if i >= 2 and i < 4:
    print("mayor o igual que dos!")
  elif i == 5:
    print("igual a 5!")



iteracion:  0
iteracion:  1
iteracion:  2
mayor o igual que dos!
iteracion:  3
mayor o igual que dos!
iteracion:  4
iteracion:  5
igual a 5!


In [ ]:
for i in range(6):
  print("iteracion: ", i)
  if i >= 2 and i < 4:
    print("mayor o igual que dos!")
  elif i == 4:
    print("igual a 4!")
  elif i == 5:
    print("igual a 5!")

iteracion:  0
iteracion:  1
iteracion:  2
mayor o igual que dos!
iteracion:  3
mayor o igual que dos!
iteracion:  4
igual a 4!
iteracion:  5
igual a 5!


In [ ]:
for i in range(6):
  print("iteracion: ", i)
  if i >= 0 and i < 4:
    print("mayor o igual que dos!")
  else:
    print("se acabó")
    break

iteracion:  0
mayor o igual que dos!
iteracion:  1
mayor o igual que dos!
iteracion:  2
mayor o igual que dos!
iteracion:  3
mayor o igual que dos!
iteracion:  4
se acabó


**Listas, Vectores y Matrices en $\mathtt{python}$**

**Listas**

In [ ]:
# Diferentes formas de crear listas

# creando una lista vacía
lista_1 = list()

observando que tiene dentro

In [ ]:
lista_1 

[]

ingresando elementos a la lista

In [ ]:
lista_1.append(1)

revisamos

In [ ]:
lista_1

[1]

In [ ]:
print("El largo de la lista es: ")
print(len(lista_1))

El largo de la lista es: 
1


Podemos agregar diferentes tipos de datos, por ejemplo, strings:

In [ ]:
lista_1.append("casa")

In [ ]:
print("El largo de la lista es: ")
print(len(lista_1))

El largo de la lista es: 
2


In [ ]:
lista_1

[1, 'casa']

para llamar elemntos de la lista, debemos tener presente que los índices comienzan en cero!



In [ ]:
lista_1[0]

1

In [ ]:
lista_1[1]

'casa'

otra forma de crear una lista

In [ ]:
lista_2 = []

In [ ]:
lista_2.append(lista_1[1])

In [ ]:
lista_2

['casa']

es posible realizar algunas operaciones entre listas!, por ejemplo multiplicar por un escalar

In [ ]:
lista_2*3

['casa', 'casa', 'casa']

sumar listas

In [ ]:
lista_2 + lista_1

['casa', 1, 'casa']

**Vectores**

Una librería comunmente utilizada para trabajar vectores y matrices es $\mathtt{numpy}$. Es una librería orientada a este tipo de objetos y en general, a diferentes herramientas del álgebra lineal. Más adelante veremos por qué es muy necesario entender y trabajar con álgebra lineal. Entonces, ahora crearé listas de números que serán operadas bajo la perspectiva del álgebra lineal.

Importamos la librería (para instalarla en localmente, debemos tener python instalado y pip). Una vez instalado eso bastaría colocar en la terminal $\mathtt{pip}$ $\mathtt{install}$ $\mathtt{numpy}$

In [ ]:
import numpy

Podemos crear una lista numérica, como hicimos anteriormente y "transformarla" a un vector. Para ver esta diferencia veamos el siguiente ejemplo:

In [ ]:
x_lista = [1,2,3,-1]

ahora como vector:

In [ ]:
x_vector = numpy.asarray([x_lista])

In [ ]:
x_vector

array([[ 1,  2,  3, -1]])

sumemos ```x_lista``` con si misma:

In [ ]:
x_lista+ x_lista

[1, 2, 3, -1, 1, 2, 3, -1]

ahora sumemos ```x_vector``` con él mismo:

In [ ]:
x_vector + x_vector

array([[ 2,  4,  6, -2]])

creemos otro vector y restemos el vector ```x_vector``` con este nuevo elemento, para esto utilizaremos la función ```numpy.ones``` que permite crear vectores de unos, solo debemos colocar correctamente las dimensiones. El vector ```x_vector``` tiene una línea y cuatro columnas, entonces usaremos $(1,4)$:

In [ ]:
y_vector = numpy.ones((1,4))

In [ ]:
y_vector

array([[1., 1., 1., 1.]])

Ahora sumamos

In [ ]:
x_vector + y_vector

array([[2., 3., 4., 0.]])

**Operaciones de álgebra lineal** 

*Producto Interno*

Una operación básica es el producto punto entre dos vectores. Matemáticamente dados dos vectores $\mathbf{x}$ e $\mathbf{y}\in \mathbb{R}^{N}$ (dos vectores de dimensión $N$ o con $N$ elementos) el producto $f: \mathbb{R}^{N}\times \mathbb{R}^{N}\rightarrow \mathbb{R}$ es dado por:

\begin{equation}
  f(\mathbf{x},\mathbf{y}) = \langle \mathbf{x}, \mathbf{y} \rangle = \displaystyle \sum_{i = 1}^{N} x_{i}y_{i}
\end{equation}

que representa la multiplicación componente a componente de los elementos de los vectores $\mathbf{x}$ e $\mathbf{y}$ y luego la suma de estas multiplicaciones, por ejemplo:

\begin{equation}
  f([1,2],[-1,4]) = \langle [1,2], [-1,4]\rangle = \displaystyle \sum_{i = 1}^{N} x_{i}y_{i} = 1\cdot -1 + 2 \cdot 4 = -1 + 8 = 7
\end{equation}

comunmente se utiliza el símbolo $\langle \cdot, \cdot \rangle$

En $\mathtt{numpy}$ podemos calcularlo así:

In [ ]:
numpy.dot(x_vector,x_vector.T)

array([[15]])

la función ```.T``` aplica la transposición del vector (Lo transforma en un vector columna). Esto porque, debido a las reglas del álgebra lineal, las dimensiones internas de los vectores deben ser iguales para poder aplicar esta operación, por ejemplo en este caso: $(1,\mathbf{4}) \times (\mathbf{4},1)$, los números en negrito se llaman *dimensiones internas* y ellas deben coincidir. Si no realizamos transposición tendríamos  $(1,\mathbf{4}) \times (\mathbf{1},4)$ lo que arrojaría **el siguiente error**:

In [ ]:
numpy.dot(x_vector,x_vector)

ValueError: ignored

*Tamaño o dimensión*

Para saber cuánto mide un vector podemos utilizar la función *shape*

In [ ]:
x_vector.shape

In [ ]:
y_vector.shape

**Matrices**

Las matrices son arreglos en dos dimensiones ([link](https://en.wikipedia.org/wiki/Matrix_(mathematics))). Particularmente, usaremos arreglos numéricos. Cuando las matrices tienen "profundidad" se les llama tensores, que aunque no son concretamente tensores, comparten algunas características comunes con los tensores matemáticos ([link sobre tensores](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial)). Por ejemplo:

In [ ]:
matriz_de_unos = numpy.ones((4,4))

In [ ]:
matriz_de_unos

In [ ]:
matriz_de_unos.shape

podemos multiplicar matrices o vectores por escalares!

In [ ]:
matriz_de_dos = 2 * matriz_de_unos

In [ ]:
matriz_de_dos

In [ ]:
matriz_de_ceros = numpy.zeros((5,5))

In [ ]:
matriz_de_ceros

*Suma de Matrices*

In [ ]:
matriz_de_dos + matriz_de_unos

*Multiplicación de Matrices*

En este caso también necesitamos respetar la regla de las dimensiones internas!.
Matemáticamente dadas dos matrices $A\in \mathbb{R}^{K\times N}$ y $B\in \mathbb{R}^{N\times D}$, el producto $g: \mathbb{R}^{K\times N}\times \mathbb{R}^{N\times D}\rightarrow {R}^{K \times D}$ es dado por:

\begin{equation}
  g\left(A,B \right) = (A B)_{ij} = \displaystyle \sum_{k = 1}^{N} a_{ik}b_{kj}
\end{equation}

para "memorizar" esta fórmula, generalmente se piensa en "multiplicar filas de la matriz $A$ por las columnas de la matriz $B$" pero esta cuando hablamos de "multiplicar" nos referimos al producto interno. Por ejemplo:

In [ ]:
matriz_de_7 = 7*numpy.ones((6,4))

In [ ]:
matriz_de_7.shape

In [ ]:
matriz_de_unos.shape

para multiplicar utilizamos el símbolo @

In [ ]:
multiplicacion = matriz_de_7@matriz_de_unos

In [ ]:
multiplicacion.shape

ejemplo más pequeños con variedad de números

In [ ]:
A = numpy.asarray([[1,2],[3,4]])
B = numpy.asarray([[2,-1],[-4,0]])

In [ ]:
A

In [ ]:
B

In [ ]:
A@B

Observemos otro caso!

In [ ]:
matriz_de_6 = 6*numpy.ones((4,4))
matriz_de_4 = 4*numpy.ones((4,4))

In [ ]:
matriz_de_6 

In [ ]:
matriz_de_4

ahora usaremos el operador *

In [ ]:
matriz_de_6 * matriz_de_4

Para el ejemplo anterior:

In [ ]:
A*B

¿Cuál es la diferencia entre * y @ ? 

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2,1,5],[1,2,1],[2,1,3]])
b = np.array([[20],[10],[15]])

In [ ]:
np.linalg.inv(A)@b

array([[2.5],
       [2.5],
       [2.5]])