# Construyendo Funciones

In [6]:
def nombre(x: float,y: float,z: float):
  '''
    Suma de tres números
  '''
  return x+y+z

In [7]:
help(nombre)

Help on function nombre in module __main__:

nombre(x: float, y: float, z: float)
    Suma de tres números



In [8]:
nombre(1,2,'hola')

TypeError: ignored

In [32]:
import numpy as np
import typing
from typing import List, Tuple

def svd_nico(X: np.array ,full_matrices = False, more_matrices = True)-> Tuple[np.array]:
  '''
    SVD de mi forma
  '''
  U,S,V = np.linalg.svd(X,full_matrices = full_matrices)
  if not more_matrices:
    return S
  if more_matrices:
    return U,S,V

In [33]:
M = np.random.rand(2,2)

In [34]:
svd_nico(M, more_matrices = True)

(array([[-0.66517937, -0.7466836 ],
        [-0.7466836 ,  0.66517937]]),
 array([1.02130102, 0.1302729 ]),
 array([[-0.14294698, -0.98973035],
        [ 0.98973035, -0.14294698]]))

In [12]:
help(np.linalg.svd)

Help on function svd in module numpy.linalg:

svd(a, full_matrices=True, compute_uv=True, hermitian=False)
    Singular Value Decomposition.
    
    When `a` is a 2D array, it is factorized as ``u @ np.diag(s) @ vh
    = (u * s) @ vh``, where `u` and `vh` are 2D unitary arrays and `s` is a 1D
    array of `a`'s singular values. When `a` is higher-dimensional, SVD is
    applied in stacked mode as explained below.
    
    Parameters
    ----------
    a : (..., M, N) array_like
        A real or complex array with ``a.ndim >= 2``.
    full_matrices : bool, optional
        If True (default), `u` and `vh` have the shapes ``(..., M, M)`` and
        ``(..., N, N)``, respectively.  Otherwise, the shapes are
        ``(..., M, K)`` and ``(..., K, N)``, respectively, where
        ``K = min(M, N)``.
    compute_uv : bool, optional
        Whether or not to compute `u` and `vh` in addition to `s`.  True
        by default.
    hermitian : bool, optional
        If True, `a` is assumed to be

Ejemplo 1

In [ ]:
def hola_n_veces(n):
  """ Imprime hola n-veces"""
  print('hola '*n)

In [ ]:
def hola_n_veces_v01(n:int):
  """ Imprime hola n-veces"""
  print('hola '*n)

In [ ]:
hola_n_veces(4)

hola hola hola hola 


Ejemplo 2

In [ ]:
def fib(n): 
    """Imprime n términos de la serie Fibonacci."""
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

In [ ]:
fib(4)

0 1 1 2 3 


Ejemplo 3

El primer argumento de esta función es proporcionado por el usuario.
Los otros dos tienen valores por defecto, que pueden ser modificados al darle los valores de entrada a la función si asi se quiere.

In [ ]:
def ask_ok(prompt, retries=4, reminder='Intentalo de nuevo!'):
    while True:
        ok = input(prompt)
        if ok in ('s', 'si', 'sip'):
            return True
        if ok in ('n', 'no', 'nop', 'nope'):
            return False
        retries = retries - 1
        if retries < 0:
            raise ValueError('respuesta inválida')
        print(reminder)

In [ ]:
ask_ok('te quieres salir del curso?')

te quieres salir del curso?no


False

In [ ]:
ask_ok('te quieres salir del curso?')

te quieres salir del curso?si


True

In [ ]:
ask_ok('te quieres salir del curso?')

te quieres salir del curso?sdsf
Intentalo de nuevo!
te quieres salir del curso?sdfdsf
Intentalo de nuevo!
te quieres salir del curso?sdfdsf
Intentalo de nuevo!
te quieres salir del curso?sdfdsf
Intentalo de nuevo!
te quieres salir del curso?sdfs


ValueError: ignored


Ejemplo 4

Argumentos posicionales

In [ ]:
def parrot(voltage, state='a stiff', action='voom', type='Norwegian Blue'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.")
    print("-- Lovely plumage, the", type)
    print("-- It's", state, "!")

In [ ]:
parrot(1000)                                          # 1 positional argument

-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !


In [ ]:
parrot(voltage=1000)                                  # 1 keyword argument

-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !


In [ ]:
parrot(voltage=1000000, action='VOOOOOM')             # 2 keyword arguments

-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !


In [ ]:
parrot('a million', 'bereft of life', 'jump')         # 3 positional arguments

-- This parrot wouldn't jump if you put a million volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's bereft of life !


In [ ]:
parrot('a thousand', state='pushing up the daisies')  # 1 positional, 1 keyword

-- This parrot wouldn't voom if you put a thousand volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's pushing up the daisies !


Formas Inválidas

In [ ]:
parrot()                     # required argument missing
parrot(voltage=5.0, 'dead')  # non-keyword argument after a keyword argument
parrot(110, voltage=220)     # duplicate value for the same argument
parrot(actor='John Cleese')  # unknown keyword argument

SyntaxError: ignored

Entregando argumentos a través de diccionarios

In [ ]:
def cheeseshop(kind, *arguments, **keywords):
    print("-- Do you have any", kind, "?")
    print("-- I'm sorry, we're all out of", kind)
    for arg in arguments:
        print(arg)
    print("-" * 40)
    for kw in keywords:
        print(kw, ":", keywords[kw])

In [ ]:
cheeseshop("Limburger", "It's very runny, sir.",
           "It's really very, VERY runny, sir.",
           shopkeeper="Michael Palin",
           client="John Cleese",
           sketch="Cheese Shop Sketch")

-- Do you have any Limburger ?
-- I'm sorry, we're all out of Limburger
It's very runny, sir.
It's really very, VERY runny, sir.
----------------------------------------
shopkeeper : Michael Palin
client : John Cleese
sketch : Cheese Shop Sketch


In [ ]:
def recapitulando(texto, *argumentos, **palabras_clave):
  print("Hemos aprendido algo sobre", texto, "?")
  print("Creo que no sé si hemos aprendido algo sobre", texto)
  for arg in argumentos:
    print(arg)
  print("-" * 40)
  for kw in palabras_clave:
    print(kw, ":", palabras_clave[kw])

In [ ]:
recapitulando("programación","increíble, todo este tiempo perdido",integrantes = ' Profesor', numero_de_estudiantes = 10)

Hemos aprendido algo sobre programación ?
Creo que no sé si hemos aprendido algo sobre programación
increíble, todo este tiempo perdido
----------------------------------------
integrantes :  Profesor
numero_de_estudiantes : 10


# Funciones Lambda

In [ ]:
def sumador_incremental(n):
    return lambda x: x + n

In [ ]:
f = sumador_incremental(17)

In [ ]:
f(0)

17

In [ ]:
f(20)

37

In [ ]:
f(23)

40

In [ ]:
x = lambda a : a + 10
print(x(5))

15


In [ ]:
x = lambda a, b : a * b
print(x(5, 6))

30


In [ ]:
f = lambda a,b,c,x: a*x**2+ b*x + c
print(f(1,0,0,3))

9
